GET http://localhost:12121/article/5

<> 2022-03-06T210301.404.json

###

GET http://localhost:12121/article/id

<> 2022-03-06T210245.500.json

###

GET http://localhost:12121/article/{{5}}

###

GET http://localhost:12121/article/{{id}}

###

GET http://localhost:12121/article/{{id}}

###

GET http://localhost:12121/article

<> 2022-03-06T203954.200.json

###

GET http://localhost:12121

<> 2022-02-28T231312.200.json

###

GET http://localhost/show

<> 2022-02-21T204040.404.json

###

GET http://localhost/show

<> 2022-02-21T204033.404.json

###

GET http://localhost/show

<> 2022-02-21T203959.404.json

###

GET http://localhost/a

###

