server:
  port: 12121  #端口服务配置
  error:
    whitelabel:
      enabled: false
#数据库配置
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://sccdqz.ltd:3306/Miniature_Broccoli
      username: root
      password: sccdqz.com
  #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
  mvc:
    throw-exception-if-no-handler-found: true
  #不要为我们工程中的资源文件建立映射
  web:
    resources:
      add-mappings: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true
mica:
  xss:
    enabled: true
    path-patterns: /**