spring:
  profiles:
    active: dev
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://sccdqz.ltd:3306/Miniature_Broccoli
      username: root
      password: sccdqz.com
  mvc:
    #出现错误时, 直接抛出异常(便于异常统一处理，否则捕获不到404)
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**


    #不要为我们工程中的资源文件建立映射
  web:
    resources:
      static-locations: classpath:/static/
      addcomment-mappings: false
mica:
  xss:
    enabled: true
    path-patterns: /**
##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800000
